[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_hook_vault_litesvm = "3ZktYLqFLBuLdzsnH66siTLjZctKzj1aZHvG9KWyaF1x"
vault= "B5ufbureiHZzc2WTW6CVqsdpQnNPyWLbBUUa9KweTxYJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cd programs/test && cargo test -- --nocapture"
